import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { motion } from 'framer-motion';
import { 
  Sparkles, 
  Target, 
  TrendingUp, 
  Clock, 
  Shield, 
  Download,
  Sun,
  Moon,
  Bot
} from 'lucide-react';

export default function Home() {
  const { isAuthenticated } = useAuth();

  const features = [
    {
      icon: <Bot className="w-8 h-8 text-primary-500" />,
      title: 'AI-Powered Plans',
      description: 'Personalized 7-day diet plans generated by advanced AI based on your unique health profile'
    },
    {
      icon: <Target className="w-8 h-8 text-primary-500" />,
      title: 'Multiple Goals',
      description: 'Choose from fat loss, muscle gain, or weight maintenance with customized calorie targets'
    },
    {
      icon: <TrendingUp className="w-8 h-8 text-primary-500" />,
      title: 'Track Progress',
      description: 'Monitor your BMI trends and calorie intake with beautiful interactive graphs'
    },
    {
      icon: <Clock className="w-8 h-8 text-primary-500" />,
      title: 'Diet History',
      description: 'Access all your previous diet plans and track your journey over time'
    },
    {
      icon: <Download className="w-8 h-8 text-primary-500" />,
      title: 'Export to PDF',
      description: 'Download your diet plans as professional PDFs to share with your nutritionist'
    },
    {
      icon: <Shield className="w-8 h-8 text-primary-500" />,
      title: 'Secure & Private',
      description: 'Your health data is encrypted and never shared with third parties'
    }
  ];

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center space-y-8 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 mb-6">
            <Sparkles className="w-4 h-4" />
            <span className="text-sm font-medium">AI-Powered Nutrition</span>
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold font-display mb-6 bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
            NutriPlan AI
          </h1>
          
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto mb-8">
            Your personal AI nutritionist that creates customized 7-day diet plans based on your unique health profile, goals, and preferences.
          </p>
          
          <div className="flex gap-4 justify-center">
            {isAuthenticated ? (
              <Link
                to="/dashboard"
                className="px-8 py-4 bg-primary-600 hover:bg-primary-700 text-white rounded-2xl font-semibold transition-all transform hover:scale-105 shadow-lg"
              >
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link
                  to="/register"
                  className="px-8 py-4 bg-primary-600 hover:bg-primary-700 text-white rounded-2xl font-semibold transition-all transform hover:scale-105 shadow-lg"
                >
                  Get Started Free
                </Link>
                <Link
                  to="/login"
                  className="px-8 py-4 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 text-gray-900 dark:text-white rounded-2xl font-semibold transition-all transform hover:scale-105 shadow-lg"
                >
                  Sign In
                </Link>
              </>
            )}
          </div>
        </motion.div>

        {/* Hero Image Placeholder */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="relative max-w-4xl mx-auto"
        >
          <div className="aspect-video rounded-3xl bg-gradient-to-br from-primary-400/20 to-secondary-400/20 dark:from-primary-900/40 dark:to-secondary-900/40 backdrop-blur-sm border border-gray-200 dark:border-gray-700 shadow-2xl overflow-hidden">
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center">
                <Bot className="w-16 h-16 mx-auto text-primary-500 mb-4" />
                <p className="text-gray-600 dark:text-gray-300">AI Generated Diet Plans • BMI Tracking • Analytics</p>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Features Grid */}
      <section className="py-16">
        <h2 className="text-3xl font-bold text-center mb-12 font-display">
          Everything You Need for Your Health Journey
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="glass-card rounded-3xl p-6 hover:shadow-2xl transition-all"
            >
              <div className="mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-600 dark:text-gray-400">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 bg-gradient-to-r from-primary-50 to-secondary-50 dark:from-gray-900 dark:to-gray-800 rounded-3xl p-8">
        <h2 className="text-3xl font-bold text-center mb-12 font-display">
          How NutriPlan AI Works
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              step: '1',
              title: 'Create Profile',
              description: 'Enter your age, height, weight, activity level, and health goals'
            },
            {
              step: '2',
              title: 'AI Analysis',
              description: 'Our AI analyzes your data to calculate BMI and nutritional needs'
            },
            {
              step: '3',
              title: 'Get Your Plan',
              description: 'Receive a personalized 7-day diet plan with Indian cuisine options'
            }
          ].map((item, index) => (
            <div key={index} className="text-center">
              <div className="w-16 h-16 rounded-2xl bg-primary-600 text-white text-2xl font-bold flex items-center justify-center mx-auto mb-4">
                {item.step}
              </div>
              <h3 className="text-xl font-semibold mb-2">{item.title}</h3>
              <p className="text-gray-600 dark:text-gray-400">{item.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="text-center py-16">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl font-bold mb-4 font-display">
            Ready to Transform Your Health?
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-400 mb-8">
            Join thousands of users who have achieved their health goals with AI-powered personalized nutrition plans.
          </p>
          
          {!isAuthenticated && (
            <Link
              to="/register"
              className="inline-flex items-center gap-2 px-8 py-4 bg-primary-600 hover:bg-primary-700 text-white rounded-2xl font-semibold transition-all transform hover:scale-105 shadow-lg"
            >
              <Sparkles className="w-5 h-5" />
              Create Your Free Account
            </Link>
          )}
        </div>
      </section>
    </div>
  );
}