import React from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { X, Download } from 'lucide-react';
import { motion } from 'framer-motion';

export default function PDFDownload({ plan, profile, onClose }) {
  const generatePDF = async () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(24);
    doc.setTextColor(34, 197, 94);
    doc.text('NutriPlan AI', 105, 20, { align: 'center' });
    
    // Subtitle
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Personalized AI Diet Plan', 105, 30, { align: 'center' });
    
    // User Info
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated for: ${profile.name}`, 20, 45);
    doc.text(`Date: ${new Date(plan.createdAt).toLocaleDateString()}`, 20, 52);
    
    // Profile Summary
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Your Profile', 20, 65);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const profileData = [
      [`Age: ${profile.age}`, `Gender: ${profile.gender}`],
      [`Height: ${profile.height}cm`, `Weight: ${profile.weight}kg`],
      [`BMI: ${profile.bmi} (${profile.bmiCategory})`, `Goal: ${profile.goal}`],
      [`Food Type: ${profile.foodType}`, `Daily Calories: ${profile.dailyCalorieTarget} kcal`]
    ];
    
    let yPos = 75;
    profileData.forEach(row => {
      doc.text(row[0], 20, yPos);
      doc.text(row[1], 105, yPos);
      yPos += 7;
    });
    
    // Diet Plan Table
    yPos += 10;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('7-Day Diet Plan', 20, yPos);
    
    // Helper to safely get meal info (handles both object and array)
    const getMeal = (meal) => {
      if (!meal) return { name: 'N/A', calories: 0 };
      if (Array.isArray(meal)) {
        return {
          name: meal.map(m => m?.name || '').filter(Boolean).join(', ') || 'N/A',
          calories: meal.reduce((sum, m) => sum + (m?.calories || 0), 0)
        };
      }
      return { name: meal.name || 'N/A', calories: meal.calories || 0 };
    };

    const tableData = plan.days.map(day => {
      const breakfast = getMeal(day.breakfast);
      const lunch = getMeal(day.lunch);
      const dinner = getMeal(day.dinner);
      const snacks = getMeal(day.snacks);
      return [
        day.day || '',
        `${breakfast.name}\n(${breakfast.calories} cal)`,
        `${lunch.name}\n(${lunch.calories} cal)`,
        `${dinner.name}\n(${dinner.calories} cal)`,
        `${snacks.name}\n(${snacks.calories} cal)`,
        `${day.totalCalories || 0} kcal`
      ];
    });

    
    autoTable(doc, {
      startY: yPos + 5,
      head: [['Day', 'Breakfast', 'Lunch', 'Dinner', 'Snacks', 'Total']],
      body: tableData,
      theme: 'grid',
      styles: {
        fontSize: 8,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [34, 197, 94],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 35 },
        2: { cellWidth: 35 },
        3: { cellWidth: 35 },
        4: { cellWidth: 30 },
        5: { cellWidth: 20 },
      },
    });
    
    // Health Tips
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Health Tips', 20, finalY);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    let tipY = finalY + 7;
    plan.healthTips.forEach((tip, index) => {
      doc.text(`${index + 1}. ${tip}`, 25, tipY);
      tipY += 6;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by NutriPlan AI - Your Personal AI Nutritionist', 105, 280, { align: 'center' });
    
    // Save PDF - let user choose location
    const fileName = `NutriPlan-${(profile?.name || 'User').replace(/\s+/g, '-')}-${new Date().toLocaleDateString('en-IN').replace(/\//g, '-')}.pdf`;
    
    if (window.showSaveFilePicker) {
      try {
        const fileHandle = await window.showSaveFilePicker({
          suggestedName: fileName,
          types: [{ description: 'PDF Document', accept: { 'application/pdf': ['.pdf'] } }]
        });
        const writableStream = await fileHandle.createWritable();
        const pdfBlob = doc.output('blob');
        await writableStream.write(pdfBlob);
        await writableStream.close();
        onClose(); // ✅ auto close after save
      } catch (err) {
        if (err.name !== 'AbortError') {
          doc.save(fileName);
          onClose(); // ✅ auto close after fallback save
        }
        // if AbortError (user cancelled dialog) — do NOT close
      }
    } else {
      doc.save(fileName);
      onClose(); // ✅ auto close after download
    }

  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="glass-card rounded-3xl p-6 max-w-md w-full"
        onClick={e => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold">Download PDF</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-gray-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        
        <p className="text-gray-600 dark:text-gray-400 mb-6">
          Your PDF will include your profile information, the complete 7-day diet plan, and health tips.
        </p>
        
        <button
          onClick={generatePDF}
          className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-xl font-semibold transition-all"
        >
          <Download className="w-5 h-5" />
          Generate PDF
        </button>
      </motion.div>
    </motion.div>
  );
}